<?php

namespace App\Http\Requests;

use App\Enums\StatusEnum;
use App\Models\DiscountType;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreSaleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            // Generated by the terminal before submitting. Not unique here:
            // a repeat is an idempotent retry, not a validation failure.
            'uuid' => ['required', 'uuid'],
            'branch_id' => ['required', 'integer', 'exists:branches,id'],
            'customer_id' => ['nullable', 'integer', 'exists:customers,id'],
            'amount_tendered' => ['nullable', 'numeric', 'min:0'],

            'items' => ['required', 'array', 'min:1'],
            'items.*.product_id' => ['required', 'integer', 'exists:products,id'],
            'items.*.product_unit_id' => ['required', 'integer', 'exists:product_units,id'],
            'items.*.quantity' => ['required', 'numeric', 'gt:0'],
            'items.*.unit_price' => ['nullable', 'numeric', 'min:0'],
            'items.*.line_discount' => ['nullable', 'numeric', 'min:0'],

            'payments' => ['required', 'array', 'min:1'],
            'payments.*.method' => ['required', Rule::in(['cash', 'gcash', 'credit'])],
            'payments.*.amount' => ['required', 'numeric', 'gt:0'],
            'payments.*.reference_no' => ['nullable', 'string', 'max:64'],

            'discounts' => ['nullable', 'array'],
            // Table-backed, and active-only: a switched-off promo must be
            // refused at the edge rather than silently discounting nothing.
            'discounts.*.type' => [
                'required',
                Rule::exists('discount_types', 'slug')
                    ->where('status', StatusEnum::ACTIVE->value)
                    ->whereNull('deleted_at'),
            ],
            'discounts.*.percentage' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'discounts.*.amount' => ['nullable', 'numeric', 'min:0'],
            'discounts.*.sale_item_id' => ['nullable', 'integer'],
            // The senior/PWD logbook.
            'discounts.*.id_number' => ['nullable', 'string', 'max:64'],
            'discounts.*.customer_name' => ['nullable', 'string', 'max:255'],
            'discounts.*.reason' => ['nullable', 'string', 'max:255'],
        ];
    }

    public function withValidator($validator): void
    {
        $validator->after(function ($validator) {
            foreach ($this->input('discounts', []) as $index => $discount) {
                $type = $discount['type'] ?? null;

                // Driven by the row, not a hardcoded pair: a store-defined
                // type that requires identification gets the same logbook
                // enforcement the statutory two do.
                if (! in_array($type, $this->identifiedSlugs(), true)) {
                    continue;
                }

                // The law asks for a logbook, not just a percentage.
                foreach (['id_number', 'customer_name'] as $field) {
                    if (blank($discount[$field] ?? null)) {
                        $validator->errors()->add(
                            "discounts.{$index}.{$field}",
                            'A senior or PWD discount requires the ID number and name on record.',
                        );
                    }
                }
            }
        });
    }

    /**
     * @return list<string>
     */
    private function identifiedSlugs(): array
    {
        return DiscountType::query()
            ->where('requires_identification', true)
            ->pluck('slug')
            ->all();
    }
}
